### ISSUE TITLE
Make another with MusicBrainz

### ISSUE THREAD

**Issue by tracymu** [tracymu/api-tutorial#7]
Do the same thing, but with having to use the steps from previous, so it's not just copy and paste

**Comment by tracymu** [comment]
Hey @puyo 
Did you say you had used MusicBrainz in an API tutorial before? 

I can only see some JSON in a beta, where you already have the ID for the artist (?) and then you can request some JSON on that particular record.

But to get the ID, you have to make a request and get an XML response first.

I'm not sure, do you think we should be introducing XML format to them?

**Comment by puyo** [comment]
Oh yeah, it is in XML. I thought it was JSON but I must have been getting
mixed up with the Spotify API. Sorry!

Should we introduce XML... good question... I thought the world was moving
away from XML but it's 2017 and we still have XML APIs so maybe it's worth
learning it still? But I think our high level goal was "funspiration" not
"actually learn all the nitty gritty details you actually need" so we
should stick to JSON so they can have fun and not get bogged down in
details.

**Comment by tracymu** [comment]
Ok Cool. Thanks @puyo  I agree with you.
